### ISSUE TITLE
Invalid syntax when running sync_app

### ISSUE THREAD

**Issue by Tak-MK** [tsudoko/anki-sync-server#5]
Hi!

I'm trying to get this working with python3 (won't even adduser with python2) but I got stuck on last step while running `python3 ankisyncd/sync_app.py ankisyncd.conf`:
```
File "ankisyncd/sync_app.py", line 116
    print(f"applyGraves chunk: {chunk}")
                                      ^
SyntaxError: invalid syntax
```
I tried to comment out that line (I don't know about python at all, so I did it just to try) and I got this:
```
Traceback (most recent call last):
  File "ankisyncd/sync_app.py", line 36, in <module>
    import anki.db
ImportError: No module named 'anki'
```

Thanks a lot!

**Comment by tsudoko** [comment]
That was a debug print I forgot to remove, `f""` strings work only on Python 3.6 and later, but `ankisyncd` is supposed to work fine on Python 3.5+.

You need to install Anki (2.1.1 or later). `ankisyncd` looks in `/usr/share/anki` and `./anki-bundled` for the `anki` module. I've updated the README, let me know if something's still unclear.

**Comment by colonelsmoothie** [comment]
One thing that worked for me, was first installing from source - which was tough for me to do. I've gotten it to work with modern versions of Ubuntu (17.04 and 18.04, but not 16.04). Damien's guide for developers helped me a bit:

https://github.com/dae/anki/blob/master/README.development

I was still getting the same error after installing as @Tak-MK , so one thing I had to do was put the Anki and ankisyncd modules in one of the PYTHONPATH directories:

``sudo cp -r /home/test/anki-sync-server/anki-bundled/anki /usr/local/lib/python3.6/dist-packages
sudo cp -r /home/test/anki-sync-server/ankisyncd /usr/local/lib/python3.6/dist-packages``

I'd like to add that one further issue you might run into after this step is with AnkiDroid if you are trying to sync with an android device. It wasn't working for me with 2.8.3, but it did after I upgraded to 2.9alpha27.

After that, things were working for me. By the way, @tsudoko, I did try this repo after your latest changes a couple days back, and I've gotten all my devices synced up - so thanks a ton for making those changes.

**Comment by tsudoko** [comment]
> One thing that worked for me, was first installing from source - which was tough for me to do. Also, when cloning this repo, use --recursive when cloning this repo to get the anki-bundled modules.

This should be covered in README now.

> I was still getting the same error after installing as @Tak-MK , so one thing I had to do was put the Anki and ankisyncd modules in one of the PYTHONPATH directories:
> `sudo cp -r /home/test/anki-sync-server/anki-bundled/anki /usr/local/lib/python3.6/dist-packages sudo cp -r /home/test/anki-sync-server/ankisyncd /usr/local/lib/python3.6/dist-packages`

This shouldn't be needed if you run `ankisyncd` from the root repo directory (the one with `anki-bundled`, `ankisyncd`, `ankisyncctl.py` etc). I might provide a `setup.py` file for proper system-wide installs in the future.

**Comment by Tak-MK** [comment]
I'm trying again and you need to install these before the `pip install -r requirements.txt` (at least on debian):
 - python3-dev
 - portaudio19-dev

After that and the other steps, I did `python3 -m ankisyncd ankisyncd.conf` and it works! \o/

Thanks a lot!
